---
- name: Check if firewalld package is installed (on RHEL).
  command: yum list installed firewalld
  args:
    warn: false
  register: firewalld_installed
  ignore_errors: true
  changed_when: false
  when:
    - ansible_os_family == "RedHat"
    - firewall_disable_firewalld
  check_mode: false

- name: Disable the firewalld service (on RHEL, if configured).
  service:
    name: firewalld
    state: stopped
    enabled: false
  when:
    - ansible_os_family == "RedHat"
    - firewall_disable_firewalld
    - firewalld_installed.rc == 0